/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ChaosScenario } from '../types';

export const CHAOS_SCENARIOS: ChaosScenario[] = [
  {
    id: 'typo',
    category: 'CLI Syntax',
    title: 'Typo & Fuzzy Flag Matching',
    description: 'User enters misspelled commands or flags like `faultline deply --enviroment=prod`.',
    command: 'faultline deply --enviroment=prod',
    expectedError: 'ERR_CLI_INVALID_FLAG',
    exitCode: 64,
    resilienceFeature: 'Levenshtein distance matching with 1-click suggested command correction.',
    tags: ['Typos', 'Fuzzy Match', 'UX Polish'],
  },
  {
    id: 'missing-config',
    category: 'Filesystem',
    title: 'Missing Config File (ENOENT)',
    description: 'Deployment triggered when `faultline.config.json` has been deleted or moved.',
    command: 'faultline chaos missing-config',
    expectedError: 'ERR_CONFIG_NOT_FOUND',
    exitCode: 66,
    resilienceFeature: 'Sysexits EX_NOINPUT code, exact path diagnostic, and auto-init button.',
    tags: ['ENOENT', 'Sysexits 66', 'Auto-Init'],
  },
  {
    id: 'corrupt-json',
    category: 'Configuration',
    title: 'Corrupted JSON Syntax Pointer',
    description: 'Configuration file has a trailing comma or malformed syntax.',
    command: 'faultline chaos corrupt-json',
    expectedError: 'ERR_CONFIG_SYNTAX_ERROR',
    exitCode: 65,
    resilienceFeature: 'Rust/Miette-style source snippet with line, column, and ^^^^ pointers.',
    tags: ['Syntax Error', 'Visual Snippet', 'Column Pointer'],
  },
  {
    id: 'permission-denied',
    category: 'Permissions',
    title: 'Protected Secret Permission (EACCES)',
    description: 'Current user lacks read permissions on `/workspace/.env.secret` (mode: 0000).',
    command: 'faultline chaos permission-denied',
    expectedError: 'ERR_PERMISSION_DENIED',
    exitCode: 77,
    resilienceFeature: 'POSIX EX_NOPERM exit code with chmod remediation command.',
    tags: ['EACCES', 'Permissions', 'Chmod Fix'],
  },
  {
    id: 'rate-limit',
    category: 'Network',
    title: '429 Rate Limit & Exponential Backoff',
    description: 'Upstream gateway returns HTTP 429 Too Many Requests with Retry-After header.',
    command: 'faultline chaos rate-limit',
    expectedError: 'ERR_RATE_LIMIT_EXHAUSTED',
    exitCode: 75,
    resilienceFeature: 'Automatic exponential backoff retries with jitter and EX_TEMPFAIL.',
    tags: ['HTTP 429', 'Backoff', 'Retryable'],
  },
  {
    id: 'rollback',
    category: 'Transactions',
    title: 'Atomic Migration Rollback',
    description: 'Database migration fails at step 3 of 3; rollback engine restores clean state.',
    command: 'faultline migrate',
    expectedError: 'ERR_MIGRATION_FAILED_ATOMIC_ROLLBACK',
    exitCode: 65,
    resilienceFeature: 'Advisory lock release, snapshot rollback, zero half-migrated data.',
    tags: ['Atomic Undo', 'Snapshots', 'Safe State'],
  },
  {
    id: 'schema-error',
    category: 'Configuration',
    title: 'Type Schema Mismatch',
    description: 'Configuration field `database.port` is given a string instead of integer.',
    command: 'faultline chaos schema-error',
    expectedError: 'ERR_CONFIG_INVALID_SCHEMA',
    exitCode: 65,
    resilienceFeature: 'Precise schema validation with typed hint and 1-click config set fix.',
    tags: ['Schema', 'Type Check', 'Quick Fix'],
  },
  {
    id: 'sigint',
    category: 'Concurrency',
    title: 'SIGINT Signal Interruption (Ctrl+C)',
    description: 'User aborts long-running operation via Ctrl+C / SIGINT signal.',
    command: 'faultline chaos sigint',
    expectedError: 'ERR_SIGNAL_SIGINT',
    exitCode: 130,
    resilienceFeature: 'Standard POSIX 128+2 signal handling with lockfile cleanup.',
    tags: ['Signals', 'Ctrl+C', 'Exit 130'],
  },
  {
    id: 'doctor-fix',
    category: 'Configuration',
    title: 'Multi-Point Health Scan & Auto-Healing',
    description: 'Runs `faultline doctor --fix` to detect and repair all system issues at once.',
    command: 'faultline doctor --fix',
    expectedError: 'NONE (Auto-Healed)',
    exitCode: 0,
    resilienceFeature: 'Comprehensive health scanner that automatically fixes corrupt configs & permissions.',
    tags: ['Doctor', 'Auto-Repair', 'Health Check'],
  },
];
